function fig = Wcinit2()
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.

load Wcinit2

h0 = figure('Units','normalized', ...
	'Color',[0.8 0.8 0.8], ...
	'Colormap',mat0, ...
	'Name','b17.mge', ...
	'NumberTitle','off', ...
	'PointerShapeCData',mat1, ...
	'Position',[0.3359375 0.2955729166666666 0.66015625 0.6002604166666666], ...
	'Tag','Fig1', ...
	'UserData',mat2);
h1 = uimenu('Parent',h0, ...
	'Label','--->', ...
	'Tag','--->1');
h1 = uimenu('Parent',h0, ...
	'Label','&New', ...
	'Tag','&New1');
h2 = uimenu('Parent',h1, ...
	'Callback','wcinit', ...
	'Label','New &Window', ...
	'Tag','&NewNew &Window1');
h2 = uimenu('Parent',h1, ...
	'Callback','newfile', ...
	'Label','New &File', ...
	'Tag','&NewNew &File1');
h2 = uimenu('Parent',h1, ...
	'Label','New &Run', ...
	'Tag','&NewNew &Run1');
h3 = uimenu('Parent',h2, ...
	'Callback','newrun(''back'')', ...
	'Label','Back', ...
	'Tag','&NewNew &RunBack1');
h3 = uimenu('Parent',h2, ...
	'Callback','newrun(''jump'')', ...
	'Label','Jump', ...
	'Tag','&NewNew &RunJump1');
h3 = uimenu('Parent',h2, ...
	'Callback','newrun(''next'')', ...
	'Label','Next', ...
	'Tag','&NewNew &RunNext1');
h1 = uimenu('Parent',h0, ...
	'Label','Display', ...
	'Tag','Display1');
h2 = uimenu('Parent',h1, ...
	'Callback','SetZero(''menu'')', ...
	'Checked','on', ...
	'Label','Set Zero', ...
	'Tag','DisplaySet Zero1');
h2 = uimenu('Parent',h1, ...
	'Callback','Mtoggle(2)', ...
	'Checked','on', ...
	'Label','Leak Subtract', ...
	'Tag','DisplayLeak Subtract1');
h2 = uimenu('Parent',h1, ...
	'Callback','Mtoggle(3)', ...
	'Checked','on', ...
	'Label','Pulse Info', ...
	'Tag','DisplayPulse Info1');
h2 = uimenu('Parent',h1, ...
	'Callback','Mtoggle(7)', ...
	'Label','Lock Axes', ...
	'Tag','DisplayLock Axes1');
h1 = uimenu('Parent',h0, ...
	'Label','Tools', ...
	'Tag','Tools1');
h2 = uimenu('Parent',h1, ...
	'Callback','isotool(''menu'')', ...
	'Label','Isochronal', ...
	'Tag','ToolsIsochronal1', ...
	'UserData',mat3);
h2 = uimenu('Parent',h1, ...
	'Callback','exptool(''menu'')', ...
	'Label','Exp Fit', ...
	'Tag','ToolsExp Fit1');
h2 = uimenu('Parent',h1, ...
	'Callback','lopass', ...
	'Label','LoPass Filter', ...
	'Tag','ToolsLoPass Filter1');
h2 = uimenu('Parent',h1, ...
	'Callback','ascdump', ...
	'Label','ASCII Dump', ...
	'Tag','ToolsASCII Dump1');
h1 = uimenu('Parent',h0, ...
	'Callback','dumpfig', ...
	'Label','Print', ...
	'Tag','Print1');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0 0 0.5], ...
	'ForegroundColor',[1 1 0], ...
	'ListboxTop',0, ...
	'Max',2, ...
	'Position',[0 0.9300000000000001 0.2 0.07000000000000001], ...
	'String','Run: 4  Swp: 1  (-40)', ...
	'Style','edit', ...
	'Tag','EditText2');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'BackgroundColor',[0 0 0.5], ...
	'ForegroundColor',[1 1 0], ...
	'ListboxTop',0, ...
	'Max',2, ...
	'Position',[0.2 0.9300000000000001 0.2 0.07000000000000001], ...
	'String','V: -100 -10 -100 -100|D: 5 300 50 0', ...
	'Style','edit', ...
	'Tag','EditText1');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'Callback','SetZero(''button'')', ...
	'ListboxTop',0, ...
	'Position',[0.4 0.95 0.1 0.05], ...
	'String','Zero', ...
	'Tag','Pushbutton18', ...
	'UserData',[0 0 0 0]);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'Callback','ltool', ...
	'ListboxTop',0, ...
	'Position',[0.5 0.95 0.1 0.05], ...
	'String','H-Line', ...
	'Tag','Pushbutton17');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'Callback','expandx', ...
	'ListboxTop',0, ...
	'Position',[0.6 0.95 0.1 0.05], ...
	'String','Exp-X', ...
	'Tag','Pushbutton16', ...
	'UserData',0);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'Callback','expandy', ...
	'ListboxTop',0, ...
	'Position',[0.6 0.9 0.1 0.05], ...
	'String','Exp-Y', ...
	'Tag','Pushbutton15', ...
	'UserData',0);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'Callback','newswp(''back'')', ...
	'ListboxTop',0, ...
	'Position',[0.7 0.95 0.1 0.05], ...
	'String','Back', ...
	'Tag','Pushbutton14');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'Callback','newswp(''jump'')', ...
	'ListboxTop',0, ...
	'Position',[0.8 0.95 0.1 0.05], ...
	'String','Jump', ...
	'Tag','Pushbutton13');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'Callback','newswp(''next'')', ...
	'ListboxTop',0, ...
	'Position',[0.9 0.95 0.1 0.05], ...
	'String','Next', ...
	'Tag','Pushbutton12');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'Callback','newswp(''skip'')', ...
	'ListboxTop',0, ...
	'Position',[0.9 0.9 0.1 0.05], ...
	'String','Skip', ...
	'Tag','Pushbutton11');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'Callback','holdswp(''keep'')', ...
	'ListboxTop',0, ...
	'Position',[0.9 0.85 0.1 0.05], ...
	'String','Keep', ...
	'Tag','Pushbutton10');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'Callback','holdswp(''wipe'')', ...
	'ListboxTop',0, ...
	'Position',[0.9 0.8 0.1 0.05], ...
	'String','Wipe', ...
	'Tag','Pushbutton9');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'ListboxTop',0, ...
	'Position',[0.9 0.55 0.1 0.05], ...
	'String','Windows', ...
	'Tag','Pushbutton8', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'ListboxTop',0, ...
	'Position',[0.9 0.5 0.1 0.05], ...
	'String','Pk: Pulse', ...
	'Tag','Pushbutton7', ...
	'UserData','1', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'ListboxTop',0, ...
	'Position',[0.9 0.45 0.1 0.05], ...
	'String','Increment', ...
	'Tag','Pushbutton6', ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'ListboxTop',0, ...
	'Position',[0.9 0.4 0.1 0.05], ...
	'String','Reset', ...
	'Tag','Pushbutton5', ...
	'UserData',mat4, ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'Callback','average(''avg1'')', ...
	'ListboxTop',0, ...
	'Position',[0.9 0.7 0.1 0.05], ...
	'String','avg1', ...
	'Tag','Pushbutton4', ...
	'UserData',[0 0 0 0]);
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'Callback','plotavg1', ...
	'ListboxTop',0, ...
	'Position',[0.9 0.65 0.1 0.05], ...
	'String','Trsfr avg1', ...
	'Tag','Pushbutton3');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'Callback','average(''avgclear'')', ...
	'ListboxTop',0, ...
	'Position',[0.9 0.6 0.1 0.05], ...
	'String','clravg', ...
	'Tag','Pushbutton2');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'ListboxTop',0, ...
	'Position',[0.9 0.5 0.1 0.05], ...
	'String',['1SED ';'1SEO ';'1DED ';'1DFT ';'2DED ';'2DFT ';'1SAR ';'Model'], ...
	'Style','popupmenu', ...
	'Tag','PopupMenu1', ...
	'Value',1, ...
	'Visible','off');
h1 = uicontrol('Parent',h0, ...
	'Units','normalized', ...
	'ListboxTop',0, ...
	'Position',[0.9 0.45 0.1 0.05], ...
	'String','Wipe Fits', ...
	'Tag','Pushbutton1', ...
	'Visible','off');
h1 = axes('Parent',h0, ...
	'Box','on', ...
	'CameraUpVector',[0 1 0], ...
	'Color',[1 1 1], ...
	'ColorOrder',mat5, ...
	'Position',[0.15 0.05 0.7 0.8], ...
	'Tag','Axes1', ...
	'XColor',[0 0 0], ...
	'XLim',[-3 355], ...
	'XLimMode','manual', ...
	'YColor',[0 0 0], ...
	'ZColor',[0 0 0]);
h2 = line('Parent',h1, ...
	'Color',[0 0 1], ...
	'Tag','Axes1Line1', ...
	'UserData',mat6, ...
	'XData',mat7, ...
	'YData',mat8);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[175.2415254237288 -329.4277929155314 17.32050807568877], ...
	'Tag','Axes1Text4', ...
	'VerticalAlignment','cap');
set(get(h2,'Parent'),'XLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[-30.30508474576271 -76.83923705722077 17.32050807568877], ...
	'Rotation',90, ...
	'Tag','Axes1Text3', ...
	'VerticalAlignment','baseline');
set(get(h2,'Parent'),'YLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','right', ...
	'Position',[-80.36440677966102 233.3787465940054 17.32050807568877], ...
	'Tag','Axes1Text2', ...
	'Visible','off');
set(get(h2,'Parent'),'ZLabel',h2);
h2 = text('Parent',h1, ...
	'Color',[0 0 0], ...
	'HandleVisibility','off', ...
	'HorizontalAlignment','center', ...
	'Position',[175.2415254237288 158.5831062670299 17.32050807568877], ...
	'Tag','Axes1Text1', ...
	'VerticalAlignment','bottom');
set(get(h2,'Parent'),'Title',h2);
if nargout > 0, fig = h0; end
